FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN apt-get update && apt-get install -y \
     pulseaudio pavucontrol \
     audacity \
     wget \
     && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data; cd /data; wget https://www.kozco.com/tech/LRMonoPhase4.wav

RUN mkdir -p /data/test_id_2
COPY test_id_2_audio_files/* /data/test_id_2/

# Start app
COPY start.sh /start.sh
CMD ["bash", "./start.sh"]