FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN apt-get update && apt-get install -y \
     pulseaudio pulseaudio-utils gstreamer1.0 gstreamer0.10-pulseaudio \
     && apt-get clean && rm -rf /var/lib/apt/lists/*

CMD tail -f /dev/null
