FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN apt-get update && apt-get install -y \
     pulseaudio pavucontrol  \
     #gstreamer1.0 gstreamer1.0-pulseaudio pulseaudio-utils \
     && apt-get clean && rm -rf /var/lib/apt/lists/*

USER jan

CMD tail -f /dev/null
