FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN apt-get update && apt-get install -y \
     pulseaudio wget \
     && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://www.kozco.com/tech/LRMonoPhase4.wav

COPY start.sh /start.sh

CMD ["bash", "/start.sh"]