FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run

RUN apt-get update && apt-get install -y \
     bluez \
     pulseaudio pavucontrol \
     audacity \
     wget \
     && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://www.kozco.com/tech/LRMonoPhase4.wav

COPY default.pa /etc/pulse/default.pa
COPY daemon.conf /etc/pulse/daemon.conf

CMD ["pulseaudio", "-D" ]